### ISSUE TITLE
testing semantic3d dataset quickly!

### ISSUE THREAD

**Issue by shaoquanfeng** [QingyongHu/RandLA-Net#120]
I download the test2 dataset:
```
wget -c -N http://semantic3d.net/data/point-clouds/testing2/MarketplaceFeldkirch_Station4_rgb_intensity-reduced.txt.7z -P $BASE_DIR/
wget -c -N http://semantic3d.net/data/point-clouds/testing2/StGallenCathedral_station6_rgb_intensity-reduced.txt.7z -P $BASE_DIR/
wget -c -N http://semantic3d.net/data/point-clouds/testing2/sg27_station10_rgb_intensity-reduced.txt.7z -P $BASE_DIR/
wget -c -N http://semantic3d.net/data/point-clouds/testing2/sg28_Station2_rgb_intensity-reduced.txt.7z -P $BASE_DIR/
```
and then comand the ` $ python utils/data_prepare_semantic3d.py`, which is sucessful ! but when i command the `$ python main_Semantic3D.py --mode test --gpu 0`, the terminal throws the bug:
```
Load_pc_0: MarketplaceFeldkirch_Station4_rgb_intensity-reduced
main_Semantic3D.py:107: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif file_path in self.train_files:
Load_pc_1: StGallenCathedral_station6_rgb_intensity-reduced
Load_pc_2: sg27_station10_rgb_intensity-reduced
Load_pc_3: sg28_Station2_rgb_intensity-reduced

Preparing reprojection indices for validation and test
finished
Initiating input pipelines
Traceback (most recent call last):
  File "main_Semantic3D.py", line 351, in <module>
    dataset.init_input_pipeline()
  File "main_Semantic3D.py", line 310, in init_input_pipeline
    gen_function, gen_types, gen_shapes = self.get_batch_gen('training')
  File "main_Semantic3D.py", line 179, in get_batch_gen
    _, num_class_total = np.unique(np.hstack(self.input_labels[split]), return_counts=True)
  File "/home/raymond/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: need at least one array to concatenate
```

how to fix it? thanks!

**Comment by zzusunquan** [comment]
I also met the same problem. Do you hava a solution ? Thanks!

**Comment by AmarR91** [comment]
I have the same issue. An approach to remedy this problem would be very helpful.

**Comment by sahar-github** [comment]
I also have the same problem!!! however, for me this happens with following command: 
python main_Semantic3D.py --mode train --gpu 0
which is mode: train

**Comment by sahar-github** [comment]
has any body of you found already a solution for this?

**Comment by GaganBhat** [comment]
Did you end up solving this problem? @sahar-github

**Comment by akharroubi** [comment]
Hi @shqfeng 

I hope you have already solved the problem! If not, here is the explanation in this issue [80](https://github.com/QingyongHu/RandLA-Net/issues/80)

@sahar-github, to run this command (with `--train`) you must have already downloaded the # Training data, otherwise, load the pre-trained model available [here ](https://drive.google.com/open?id=1iU8yviO3TP87-IexBXsu13g6NklwEkXB)

**Comment by GaganBhat** [comment]
I found that using some other test case worked better for some odd reason. It has to do with the right folders not being found appropriately. Add prints right before the error occurs to see the state of the program and it should be clear why.

**Comment by sahar-github** [comment]
Hii
Thanks for your reply and the expkanation
I have to test this again according to your instructions
I will write you as soon as I solved the problem
Thanks again
Sahar

**Comment by obouluh** [comment]
add the data and label

**Comment by tomjierry** [comment]
He loads the training and testing sets from original_data, with the point cloud corresponding to the. labels file as the training set and only the point cloud in the txt file as the testing set.
