### ISSUE TITLE
python3.5 utils/data_prepare_s3dis.py

### ISSUE THREAD

**Issue by Timaces** [QingyongHu/RandLA-Net#134]
(RANDLA-NET) oXXXXX@oXXXXX:~/Documents/RandLA-Net-master$ python3.5 utils/data_prepare_s3dis.py 
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/conferenceRoom_1/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/conferenceRoom_2/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/copyRoom_1/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/hallway_1/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/hallway_2/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/hallway_3/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/hallway_4/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/hallway_5/Annotations
data/S3DIS/Stanford3dDataset_v1.2_Aligned_Version/Area_1/hallway_6/Annotations
sys:1: DtypeWarning: Columns (0,5) have mixed types. Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "utils/data_prepare_s3dis.py", line 81, in <module>
    convert_pc2ply(annotation_path, join(original_pc_folder, out_file_name))
  File "utils/data_prepare_s3dis.py", line 49, in convert_pc2ply
    xyz_min = np.amin(pc_label, axis=0)[0:3]
  File "<__array_function__ internals>", line 6, in amin
  File "/home/omnisky/.virtualenvs/RANDLA-NET/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/home/omnisky/.virtualenvs/RANDLA-NET/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: unorderable types: float() <= str()

who can help me? thanks

**Comment by youssef962** [comment]
@Timaces 
Have you got any solution for this?
