### ISSUE TITLE
ModuleNotFoundError: No module named 'nearest_neighbors.lib' 

### ISSUE THREAD

**Issue by makaay2077** [QingyongHu/RandLA-Net#137]
I run google colab but got this error all notebooks (data_prepare_s3dis.py , main_S3DIS.py)

Traceback (most recent call last):
  File "utils/data_prepare_s3dis.py", line 12, in <module>
    from helper_tool import DataProcessing as DP
  File "/content/RandLA-Net/helper_tool.py", line 15, in <module>
    import nearest_neighbors.lib.python.nearest_neighbors as nearest_neighbors
ModuleNotFoundError: No module named 'nearest_neighbors.lib'

**Comment by yaping222** [comment]
Hi makaay2077, I met the same issues. May I ask how did you solve it?

**Comment by makaay2077** [comment]
> 
> 
> Hi makaay2077, I met the same issues. May I ask how did you solve it?

I haven't found a solve yet

**Comment by yaping222** [comment]
> > Hi makaay2077, I met the same issues. May I ask how did you solve it?
> 
> I haven't found a solve yet

I run 'sh compile_op.sh'. Then it works.

**Comment by youssef962** [comment]
@yaping222 how did you run it? it gives me this error 
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Distutils import build_ext
ImportError: No module named Cython.Distutils
```
However, I have Cython installed !

**Comment by yaping222** [comment]
> @yaping222 how did you run it? it gives me this error
> 
> ```
> Traceback (most recent call last):
>   File "setup.py", line 3, in <module>
>     from Cython.Distutils import build_ext
> ImportError: No module named Cython.Distutils
> ```
> 
> However, I have Cython installed !

Sorry, I didn't meet this issue.

**Comment by y-sheng** [comment]
I think the package has been changed, try use 'import nearest_neighbors' directly

**Comment by 01skblue01** [comment]
事先运行 sh compile_op.sh

**Comment by zhangwanyao** [comment]
Right,you should pip install cypyton firstly,after that run sh compile_op.sh

**Comment by Zephyr-One** [comment]
Change "import nearest_neighbors.lib.python.nearest_neighbors as nearest_neighbors" to "import nearest_neighbors"
It works for me.
