### ISSUE TITLE
inference on custom data

### ISSUE THREAD

**Issue by chyohoo** [QingyongHu/RandLA-Net#138]
Hi, I used the pretrained model on S3DIS to test on my custom data. I prepared the data by following the data_preppare_s3dis and the tree file and the proj file were correctly generated. Then I used the command `python -B main_S3DIS.py --mode test --model_path /somepath/snap-26001 --gpu 0 `, then I met the following errors 

`Traceback (most recent call last):
  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 418, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 114, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_4"](arg0)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_S3DIS.py", line 254, in <module>
    tester.test(model, dataset)
  File "/home/cvhci/accMap/RandLA-Net/tester_S3DIS.py", line 78, in test
    stacked_probs, stacked_labels, point_idx, cloud_idx = self.sess.run(ops, {model.is_training: False})
  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 418, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 114, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/home/cvhci/anaconda3/envs/randlanet/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_4"](arg0)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
`
How to fix this?

**Comment by chyohoo** [comment]
Sry, it was a typo in my main_S3DIS.

**Comment by youssef962** [comment]
I'm facing the same error what was your typo please? my issue #207 
@chyohoo

**Comment by chyohoo** [comment]
> I'm facing the same error what was your typo please? my issue #207 @chyohoo

sorry, it is too long for me to recall the details. It was a typo in the file path probably.
