### ISSUE TITLE
Problem running main_semantic3D

### ISSUE THREAD

**Issue by sahar-github** [QingyongHu/RandLA-Net#145]
Hi I have a problem running the main_semantic3D.py. I followed the instructions as it was suggested. However, each time I run the routine, I see this error message, which I do not know why this happens?
python main_Semantic3D.py --mode train --gpu 0
Load_pc_0: bildstein_station1_xyz_intensity_rgb
Traceback (most recent call last):
File "main_Semantic3D.py", line 349, in 
dataset = Semantic3D()
File "main_Semantic3D.py", line 94, in init
self.load_sub_sampled_clouds(cfg.sub_grid_size)
File "main_Semantic3D.py", line 121, in load_sub_sampled_clouds
sub_labels = data['class']
ValueError: no field of name class
I would appreciate if you could give a hint, how can i solve this issue.
PS, I am using your own dataset to only test the routine, for the first time.

**Comment by tiger-bug** [comment]
Did you create the plyfiles correctly?  It looks like your plyfiles don't have a **class** field.  Line 116 reads in the plyfile and converts it to an array, but based on that error message your plyfiles don't have a class field.  If you want to quickly look at the fields of a plyfile you can ```pip install plyfile``` and with that execute the following code:

```python
from plyfile import PlyData
plytxt = '/path/to/plyfile.ply'
with open(plytxt, 'rb') as f:
    plydata = PlyData.read(f)
print(plydata.elements[0])
```
That should give you a list of the fields in the plyfile.
