### ISSUE TITLE
Custom dataset training 

### ISSUE THREAD

**Issue by abhigoku10** [QingyongHu/RandLA-Net#15]
@QingyongHu @Yang7879  thanks for sharing your wonderful work , it was of great help to me but i am having few queries regarding the training on custom dataset 
Q1. The density of points of my custom data is sparser compared to density of points in semanttic dataset so what precautions should i take when training the data using the source code 
Q2. what is the minimum number of data is required training so as to see decent enough of results 
Q3. can we overfit the model during if so which params i have tune to perform this operation 

Thanks in advance

**Comment by QingyongHu** [comment]
> @QingyongHu @Yang7879 thanks for sharing your wonderful work , it was of great help to me but i am having few queries regarding the training on custom dataset
> Q1. The density of points of my custom data is sparser compared to density of points in semanttic dataset so what precautions should i take when training the data using the source code
-Nothing special to do, train on you custom dataset first and then rethinking the data processing steps.
> Q2. what is the minimum number of data is required training so as to see decent enough of results
-I can't give you an exact answer now, but I would suggest you use as many data as possible
> Q3. can we overfit the model during if so which params i have tune to perform this operation
-Our model is not very sensitive to the parameters, I would suggest you try on your custom dataset first and then analyze the performance
> Thanks in advance

**Comment by abhigoku10** [comment]
@QingyongHu  thanks for the response i am trying to anotate my custom model . i did a small experiement where i down sampled the semanttic kitti data upto 15000 points in 360 deg view  the accuracy is good but lesser than this i am getting lots of misclassifications since  i amhaving roughly 1280 points only in the front view of the point cloud . so i am having few queries with this regard 
Q1. should we retrain the semanttic kitti dataset model with lesser points to see good detections 
Q2. by annotation of 200 frames with  1280 points in the pc will be able to get good results 
Q3. can i use sh jobs_test_semantickitti.sh to evaluate the model output with lesser points

**Comment by QingyongHu** [comment]
> Q1. should we retrain the semanttic kitti dataset model with lesser points to see good detections
You are encouraged to retrain the model, but I would suggest you should keep a similar density with your custom dataset.
> Q2. by annotation of 200 frames with 1280 points in the pc will be able to get good results
In my experience, 200 frames maybe not enough to train a robust model.
> Q3. can i use sh jobs_test_semantickitti.sh to evaluate the model output with lesser points
You do not need to use that, this script is used for when there are several sequential point clouds.

**Comment by abhigoku10** [comment]
@QingyongHu @QingyongHu thanks for the suggestion earlier , i have trained on my custom dataset with 2k frames for only class objects like car, peds,truck and there remaining points i have grouped to unlabelled dataset. below are the observations 
1.when i kept it for training for the 10th epoch i have obtained the model after which i kept on getting the following error 
****EPOCH 7****
Step 00002500 L_out=18.224 Acc=0.96 ---   54.71 ms/batch
Step 00002550 L_out=28.123 Acc=0.69 ---   50.18 ms/batch
Step 00002600 L_out=25.355 Acc=0.71 ---   52.72 ms/batch
Step 00002650 L_out=27.497 Acc=0.16 ---   48.21 ms/batch
Step 00002700 L_out=17.750 Acc=0.64 ---   59.19 ms/batch
Step 00002750 L_out=72.115 Acc=0.09 ---   56.76 ms/batch
Step 00002800 L_out=85.562 Acc=0.63 ---   61.85 ms/batch
0 / 87
/home/val/march23/march27/RandLA-Net-master_val/RandLANet.py:243: RuntimeWarning: invalid value encountered in true_divide
  iou = true_positive_classes[n] / float(gt_classes[n] + positive_classes[n] - true_positive_classes[n])
eval accuracy: 0.6109543729934819
mean IOU:nan
Mean IoU = nan%
--------------------------------------------------------------------------------------------------------------------------
  nan | 46.98   nan   nan 47.53   nan 29.21  0.00   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan
--------------------------------------------------------------------------------------------------------------------------

Best m_IoU is: 0.000
****EPOCH 8****
Step 00002850 L_out=18.439 Acc=0.92 ---   52.80 ms/batch
Step 00002900 L_out=34.015 Acc=0.41 ---   53.55 ms/batch
Step 00002950 L_out=30.689 Acc=0.61 ---   43.28 ms/batch
Step 00003000 L_out=17.752 Acc=0.83 ---   53.49 ms/batch
Caught a NaN error :
3
Expected size[0] in [0, 0], but got 1
         [[node loss/softmax_cross_entropy_with_logits_sg/Slice (defined at /RandLA-Net-master_val/RandLANet.py:265) ]]
         [[node optimizer/gradients/layers/Encoder_layer_2LFAatt_pooling_1mlp/BiasAdd_grad/BiasAddGrad (defined at /RandLA-Net-master_val/RandLANet.py:82) ]]
name: "loss/softmax_cross_entropy_with_logits_sg/Slice"
op: "Slice"
input: "loss/softmax_cross_entropy_with_logits_sg/Shape_1"
input: "loss/softmax_cross_entropy_with_logits_sg/Slice/begin"
input: "loss/softmax_cross_entropy_with_logits_sg/Slice/size"
attr {
  key: "Index"
  value {
    type: DT_INT32
  }
}
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}

loss/softmax_cross_entropy_with_logits_sg/Slice
['loss/softmax_cross_entropy_with_logits_sg/Shape_1:0', 'loss/softmax_cross_entropy_with_logits_sg/Slice/begin:0', 'loss/softmax_cross_entropy_with_logits_sg/Slice/size:0']
['loss/softmax_cross_entropy_with_logits_sg/Slice:0']
Traceback (most recent call last):
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected size[0] in [0, 0], but got 1
         [[{{node loss/softmax_cross_entropy_with_logits_sg/Slice}}]]
         [[{{node optimizer/gradients/layers/Encoder_layer_2LFAatt_pooling_1mlp/BiasAdd_grad/BiasAddGrad}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/RandLA-Net-master_val/RandLANet.py", line 160, in train
    _, _, summary, l_out, probs, labels, acc = self.sess.run(ops, {self.is_training: True})
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected size[0] in [0, 0], but got 1
         [[node loss/softmax_cross_entropy_with_logits_sg/Slice (defined at /home/val/march23/march27/RandLA-Net-master_val/RandLANet.py:265) ]]
         [[node optimizer/gradients/layers/Encoder_layer_2LFAatt_pooling_1mlp/BiasAdd_grad/BiasAddGrad (defined at /home/val/march23/march27/RandLA-Net-master_val/RandLANet.py:82) ]]

Caused by op 'loss/softmax_cross_entropy_with_logits_sg/Slice', defined at:
  File "main_SemanticKITTI.py", line 209, in <module>
    model = Network(dataset, cfg)
  File "/home/val/march23/march27/RandLA-Net-master_val/RandLANet.py", line 78, in __init__
    self.loss = self.get_loss(valid_logits, valid_labels, self.class_weights)
  File "/home/val/march23/march27/RandLA-Net-master_val/RandLANet.py", line 265, in get_loss
    unweighted_losses = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=one_hot_labels)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2561, in softmax_cross_entropy_with_logits
    labels=labels, logits=logits, axis=dim, name=name)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2370, in softmax_cross_entropy_with_logits_v2
    labels=labels, logits=logits, axis=axis, name=name)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2464, in softmax_cross_entropy_with_logits_v2_helper
    precise_logits = _flatten_outer_dims(precise_logits)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2095, in _flatten_outer_dims
    array_ops.shape(logits), [math_ops.subtract(rank, 1)], [1])
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 707, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8236, in _slice
    "Slice", input=input, begin=begin, size=size, name=name)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/val/Documents/venvs/VA/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Expected size[0] in [0, 0], but got 1
         [[node loss/softmax_cross_entropy_with_logits_sg/Slice (defined at /home/val/march23/march27/RandLA-Net-master_val/RandLANet.py:265) ]]
         [[node optimizer/gradients/layers/Encoder_layer_2LFAatt_pooling_1mlp/BiasAdd_grad/BiasAddGrad (defined at/RandLA-Net-master_val/RandLANet.py:82) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_SemanticKITTI.py", line 210, in <module>
    model.train(dataset)
  File "/RandLA-Net-master_val/RandLANet.py", line 197, in train
    a = 1 / 0
ZeroDivisionError: division by zero
2.when i tested with the 10th epoch model even the roads trees classes are getting detected as car/truck
Can you share your experience on this

**Comment by abhigoku10** [comment]
discussion is happening in #10
