### ISSUE TITLE
Error when executing code 'data_prepare_s3dis.py'

### ISSUE THREAD

**Issue by IMSHJI** [QingyongHu/RandLA-Net#160]
I downloaded the S3DIS data set, created and moved the data/S3DIS/ folder, but the following error occurred when the 'data_prepare_s3dis.py' code was executed.

![Screenshot from 2021-05-31 16-36-39](https://user-images.githubusercontent.com/76108208/120157829-6264f600-c22e-11eb-8c4d-54c37c8210f2.png)

Any idea why I'm getting the 'original_ply' error?

**Comment by IMSHJI** [comment]
There was no data related to original_ply in the S3DIS dataset.

**Comment by lmsdss** [comment]
Maybe you need to add the full path？
dataset_path =‘ ’

**Comment by youssef962** [comment]
@IMSHJI  @lmsdss 
I'm trying to run the data_prepare_s3dis python file, it shows me this error:

'''
Traceback (most recent call last):
  File "data_prepare_s3dis.py", line 80, in <module>
    convert_pc2ply(annotation_path, join(original_pc_folder, out_file_name))
  File "data_prepare_s3dis.py", line 47, in convert_pc2ply
    pc_label = np.concatenate(data_list, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
'''
any ideas?

**Comment by IMSHJI** [comment]
@youssef962 

Did you download the s3dis dataset?

if you downloaded

As long as the path is specified correctly, the preprocessing code runs without problems.

**Comment by youssef962** [comment]
@IMSHJI 
I downloaded the data and the problem is that the data_list array is empty! I printed it out and it was supposed to have the saved data but found it empty!

**Comment by youssef962** [comment]
> Maybe you need to add the full path？ dataset_path =‘ ’

I'm having the same error and i copied the full path and nothing changed!
@IMSHJI how did you solve it?
@lmsdss

**Comment by youssef962** [comment]
any help?
@IMSHJI

**Comment by IMSHJI** [comment]
@youssef962 

I don't know..
Running the code in ubuntu seems to solve it, but
The error that there is no array is considered to be caused by the Windows environment in my opinion.

**Comment by Mzzzzzzzzz** [comment]
> @IMSHJI @lmsdss I'm trying to run the data_prepare_s3dis python file, it shows me this error:
> 
> ''' Traceback (most recent call last): File "data_prepare_s3dis.py", line 80, in convert_pc2ply(annotation_path, join(original_pc_folder, out_file_name)) File "data_prepare_s3dis.py", line 47, in convert_pc2ply pc_label = np.concatenate(data_list, 0) File "<**array_function** internals>", line 6, in concatenate ValueError: need at least one array to concatenate ''' any ideas?

i got the same problem, have u find anyway to solve it?

**Comment by Kukdo** [comment]
Check your dataset path, maybe you should add ./ to redirect to your parent folder, makbe it will work.

**Comment by kryptoniancode** [comment]
Move the extracted folder to `RandLA-Net/` directory and change the path to `S3DIS/Stanford3dDataset_v1.2_Aligned_Version`.
