### ISSUE TITLE
ValueError: need at least one array to concatenate ...... while running data_prepare_s3dis

### ISSUE THREAD

**Issue by youssef962** [QingyongHu/RandLA-Net#184]
@QingyongHu 
I'm trying to run ''data_prepare_s3dis.py'' file and it's showing me this error:

'''
randla-net\data\S3DIS\Stanford3dDataset_v1.2_Aligned_Version/Area_1/conferenceRoom_1/Annotations
Traceback (most recent call last):
  File "data_prepare_s3dis.py", line 80, in <module>
    convert_pc2ply(annotation_path, join(original_pc_folder, out_file_name))
  File "data_prepare_s3dis.py", line 47, in convert_pc2ply
    pc_label = np.concatenate(data_list, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
'''
Any help please?!

**Comment by merazlab** [comment]
Hi @youssef962,
in data_prepare_s3dis.py edit data path or change to absolute path of dataset.

**Comment by youssef962** [comment]
It worked! thanks very much @merazlab

**Comment by youssef962** [comment]
please check the error I had in issue #207  if you have a solution I would be grateful
