### ISSUE TITLE
Is it possible to run this code on windows?

### ISSUE THREAD

**Issue by youssef962** [QingyongHu/RandLA-Net#191]
I want to run this code on windows, if it's possible please tell me how to solve this error :
```
****EPOCH 0****
Traceback (most recent call last):
  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: IndexError: index 319979 is out of bounds for axis 0 with size 47722
Traceback (most recent call last):

  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 418, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 123, in spatially_regular_gen
    center_point = points[point_ind, :].reshape(1, -1)

IndexError: index 319979 is out of bounds for axis 0 with size 47722


         [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_1"](arg0)]]
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_S3DIS.py", line 239, in <module>
    model.train(dataset)
  File "E:\Research\Codes\Randlanet\RandLANet.py", line 160, in train
    _, _, summary, l_out, probs, labels, acc = self.sess.run(ops, {self.is_training: True})
  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: IndexError: index 319979 is out of bounds for axis 0 with size 47722
Traceback (most recent call last):

  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\ops\script_ops.py", line 206, in __call__
    ret = func(*args)

  File "C:\Users\youss\miniconda3\envs\randlanet1\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 418, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 123, in spatially_regular_gen
    center_point = points[point_ind, :].reshape(1, -1)

IndexError: index 319979 is out of bounds for axis 0 with size 47722


         [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_1"](arg0)]]
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
```
this error appears only when I run on windows but when using ubuntu wsl on the same code it runs without this error . so how do I fix that?

**Comment by Ilyas-Malik** [comment]
Hello Youssef,

I'm encountering an issue too when running setup.py to set the environment on windows, there are many issues on windows when it comes to cutting edge research implementations.
Please let me know how it turned out for you
