### ISSUE TITLE
Error while testing unlabeled data

### ISSUE THREAD

**Issue by youssef962** [QingyongHu/RandLA-Net#207]
Hi @QingyongHu I'm trying to test my own data and it gives me this error:
```
Confusion on sub clouds
 0.00 |  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00


Reproject Vote #287
Traceback (most recent call last):
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/randlanet/tester_S3DIS.py", line 79, in test
    stacked_probs, stacked_labels, point_idx, cloud_idx = self.sess.run(ops, {model.is_training: False})
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

Caused by op 'IteratorGetNext', defined at:
  File "main_S3DIS.py", line 233, in <module>
    dataset.init_input_pipeline()
  File "main_S3DIS.py", line 213, in init_input_pipeline
    self.flat_inputs = iter.get_next()
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 420, in get_next
    name=name)), self._output_types,
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/youssef/miniconda3/envs/randlanet2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_S3DIS.py", line 253, in <module>
    tester.test(model, dataset)
  File "/mnt/d/randlanet/tester_S3DIS.py", line 140, in test
    proj_idx = dataset.val_proj[i_val]
IndexError: list index out of range
```
can you please help tell why this error is generated?
Thanks in advance.

**Comment by jtwhu** [comment]
same error, did you solve it ?
