### ISSUE TITLE
issue in python -B main_S3DIS.py --gpu 0 --mode train --test_area 1

### ISSUE THREAD

**Issue by merazlab** [QingyongHu/RandLA-Net#208]
`

Traceback (most recent call last):

  File "/home/javed/anaconda3/envs/randlanet36/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/javed/anaconda3/envs/randlanet36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 418, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 114, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/home/javed/anaconda3/envs/randlanet36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/home/javed/anaconda3/envs/randlanet36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/home/javed/anaconda3/envs/randlanet36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

         [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_1"](arg0)]]
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
         [[{{node layers/Shape_26/_49}} = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_838_layers/Shape_26", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_S3DIS.py", line 239, in <module>
    model.train(dataset)
  File "/data_hpc/userdata/javed/mwork/RandLA-Net/RandLANet.py", line 193, in train
    print(e.op.name)
AttributeError: 'NoneType' object has no attribute 'name'`

**Comment by merazlab** [comment]
I change in main_s3dis.py,  self.path variable of my dataset, but here i am enter absolute path not a relative path.

**Comment by 773041642** [comment]
Have you solved this problem?
