### ISSUE TITLE
ValueError: need at least one array to concatenate 

### ISSUE THREAD

**Issue by makaay2077** [QingyongHu/RandLA-Net#224]
Hi.First python utils/data_prepare_semantic3d.py and then
I am running main_Semantic.py but I am getting error as below. Could you please help.?

main_Semantic3D.py:89: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif file_path in self.train_files:

Preparing reprojection indices for validation and test
finished
Initiating input pipelines
Traceback (most recent call last):
  File "main_Semantic3D.py", line 333, in <module>
    dataset.init_input_pipeline()
  File "main_Semantic3D.py", line 292, in init_input_pipeline
    gen_function, gen_types, gen_shapes = self.get_batch_gen('training')
  File "main_Semantic3D.py", line 161, in get_batch_gen
    _, num_class_total = np.unique(np.hstack(self.input_labels[split]), return_counts=True)
  File "/home/ubuntu/anaconda3/envs/cagdas/lib/python3.6/site-packages/numpy/core/shape_base.py", line 340, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: need at least one array to concatenate

**Comment by ClosedOn** [comment]
I also encountered this problem. Have you solved it?

**Comment by QingyongHu** [comment]
Thanks for your interest in our work! @makaay2077 @ClosedOn 

It seems the data is not loaded correctly, please check if the data preparation is correct, and the path to the dataset is correct

I hope this could answer your question.
