### ISSUE TITLE
Windows Running error

### ISSUE THREAD

**Issue by hongzhiqiang67** [QingyongHu/RandLA-Net#225]
File "D:\Anconda\envs\randla\lib\site-packages\tensorflow\python\ops\script_ops.py", line 209, in __call__
    ret = func(*args)

  File "D:\Anconda\envs\randla\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 114, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "<__array_function__ internals>", line 6, in argmin

  File "D:\Anconda\envs\randla\lib\site-packages\numpy\core\fromnumeric.py", line 1276, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "D:\Anconda\envs\randla\lib\site-packages\numpy\core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "D:\Anconda\envs\randla\lib\site-packages\numpy\core\fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

         [[{{node PyFunc}}]]
         [[IteratorGetNext]]
         [[layers/Encoder_layer_2LFAmlp2/weights/read/_227]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_S3DIS.py", line 239, in <module>
    model.train(dataset)
  File "D:\点云算法代码\RandLA-Net-master\RandLANet.py", line 193, in train
    print(e.op.name)
AttributeError: 'NoneType' object has no attribute 'name'

How do I fix it?Thank you!

**Comment by QingyongHu** [comment]
Thanks for your interest in our work!

It seems the data is not loaded correctly, please consider removing the Chinese character in the path of the dataset.

I hope this could answer your question.

**Comment by biophase** [comment]
same or similar issue on Ubuntu 22.04 with no Chinese (or non-english) characters

solution was to add '.' to the beginning of the path

e.g.
```
class S3DIS:
    def __init__(self, test_area_idx):
        self.name = 'S3DIS'
        self.path = './data/S3DIS' # instad of '/data/S3DIS'
```
