### ISSUE TITLE
ValueError: no field of name class

### ISSUE THREAD

**Issue by haoyuting98** [QingyongHu/RandLA-Net#248]
Hi.First python utils/data_prepare_semantic3d.py and then
I am running main_Semantic.py but I am getting error as below. Could you please help.?
WARNING:tensorflow:From /home/ders/anaconda3/envs/randlanet/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Load_pc_0: bildstein_station1_xyz_intensity_rgb
Traceback (most recent call last):
File "main_Semantic3D.py", line 351, in <module>
dataset = Semantic3D()
File "main_Semantic3D.py", line 96, in __init__
self.load_sub_sampled_clouds(cfg.sub_grid_size)
File "main_Semantic3D.py", line 123, in load_sub_sampled_clouds
sub_labels = data['class']
ValueError: no field of name class

**Comment by Marine98k** [comment]
have you solve it? i have met the same problem
