### ISSUE TITLE
ERROR：out of range

### ISSUE THREAD

**Issue by yolic66** [QingyongHu/RandLA-Net#287]
****EPOCH 0****
Step 00000050 L_out=0.571 Acc=0.78 --- 1785.95 ms/batch
Step 00000100 L_out=0.379 Acc=0.90 --- 1787.15 ms/batch
Step 00000150 L_out=0.530 Acc=0.76 --- 1827.97 ms/batch
Step 00000200 L_out=0.411 Acc=0.96 --- 1828.96 ms/batch
Step 00000250 L_out=0.673 Acc=0.77 --- 1842.90 ms/batch
Step 00000300 L_out=0.297 Acc=0.95 --- 1867.79 ms/batch
Step 00000350 L_out=1.134 Acc=0.50 --- 1842.90 ms/batch
Step 00000400 L_out=0.751 Acc=0.74 --- 1861.82 ms/batch
Step 00000450 L_out=0.269 Acc=1.00 --- 1793.12 ms/batch
Step 00000500 L_out=1.235 Acc=0.31 --- 1819.35 ms/batch
0 / 100
Traceback (most recent call last):
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\client\session.py", line 1377, in _do_call
    return fn(*args)
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) OUT_OF_RANGE: End of sequence
         [[{{node IteratorGetNext}}]]
         [[layers/Encoder_layer_0LFAatt_pooling_2mlp/weights/read/_291]]
  (1) OUT_OF_RANGE: End of sequence
         [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\dell\Desktop\RandLA-Net-master\RandLANet.py", line 162, in train
    _, _, summary, l_out, probs, labels, acc = self.sess.run(ops, {self.is_training: True})
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\client\session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\client\session.py", line 1190, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\client\session.py", line 1396, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.OutOfRangeError: Graph execution error:

Detected at node 'IteratorGetNext' defined at (most recent call last):
    File "c:\Users\dell\Desktop\RandLA-Net-master\main_Semantic3D.py", line 321, in <module>
      dataset.init_input_pipeline()
    File "c:\Users\dell\Desktop\RandLA-Net-master\main_Semantic3D.py", line 301, in init_input_pipeline
      self.flat_inputs = iter.get_next()
Node: 'IteratorGetNext'
Detected at node 'IteratorGetNext' defined at (most recent call last):
    File "c:\Users\dell\Desktop\RandLA-Net-master\main_Semantic3D.py", line 321, in <module>
      dataset.init_input_pipeline()
    File "c:\Users\dell\Desktop\RandLA-Net-master\main_Semantic3D.py", line 301, in init_input_pipeline
      self.flat_inputs = iter.get_next()
Node: 'IteratorGetNext'
2 root error(s) found.
  (0) OUT_OF_RANGE: End of sequence
         [[{{node IteratorGetNext}}]]
         [[layers/Encoder_layer_0LFAatt_pooling_2mlp/weights/read/_291]]
  (1) OUT_OF_RANGE: End of sequence
         [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "c:\Users\dell\Desktop\RandLA-Net-master\main_Semantic3D.py", line 321, in <module>
    dataset.init_input_pipeline()
  File "c:\Users\dell\Desktop\RandLA-Net-master\main_Semantic3D.py", line 301, in init_input_pipeline
    self.flat_inputs = iter.get_next()
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 442, in get_next
    flat_ret = gen_dataset_ops.iterator_get_next(
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2942, in iterator_get_next
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 740, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\framework\ops.py", line 3776, in _create_op_internal
    ret = Operation(
  File "D:\software\Anaconda\envs\etmvsnet\lib\site-packages\tensorflow\python\framework\ops.py", line 2175, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\dell\Desktop\RandLA-Net-master\main_Semantic3D.py", line 325, in <module>
    model.train(dataset)
  File "c:\Users\dell\Desktop\RandLA-Net-master\RandLANet.py", line 172, in train
    m_iou = self.evaluate(dataset)
  File "c:\Users\dell\Desktop\RandLA-Net-master\RandLANet.py", line 235, in evaluate
    conf_matrix = confusion_matrix(labels_valid, pred_valid, np.arange(0, self.config.num_classes, 1))
TypeError: confusion_matrix() takes 2 positional arguments but 3 were given

**Comment by Roomnum** [comment]
Hello! I met the same problem when I input my own dataset like Semantic3D format. Did you solve it? Thanks.
