### ISSUE TITLE
Donot generated /test floder

### ISSUE THREAD

**Issue by honggesmile** [QingyongHu/RandLA-Net#40]
hi，i run: 

- sh jobs_6_fold_cv_s3dis.sh
But did not generate the test folder containing the ply file.so I can't continue to run the code.

1. “Move all the generated results (*.ply) in /test folder to /data/S3DIS/results, calculate the final mean IoU results:”

note：Generated many ply files in these folders：RandLA-Net/data/S3DIS/input_0.040/  RandLA-Net/data/S3DIS/input_0.040/original_ply

**Comment by QingyongHu** [comment]
Hi @honggesmile, thanks for your interest in our work!

> * sh jobs_6_fold_cv_s3dis.sh
>   But did not generate the test folder containing the ply file.so I can't continue to run the code.
The test folder will be created when you evaluate the performance of the trained model on a specific area, e.g.,
`python -B main_S3DIS.py --gpu 0 --mode test --test_area 1
`
Can you please give me more details about your problem?

**Comment by DRosemei** [comment]
@honggesmile  I met the same problm with you. @QingyongHu  Could you give some advice? I have generate these train_log, results and log*.txt.

**Comment by DRosemei** [comment]
I have found that this [line](https://github.com/QingyongHu/RandLA-Net/blob/398b9478650011c4284ccb25816ed598e3217325/tester_S3DIS.py#L62) will create /test folder while it did not worked.  It only created results/log*

**Comment by DRosemei** [comment]
I have solved this problem. 
I use `python -B main_S3DIS.py --gpu 0 --mode test --test_area 1 --model_path results/Log_2020-03-31_07-53-08/snapshots/snap-33501` to test Area1 and test other areas respectively. But I still do not know why it did not work in "jobs_6_fold_cv_s3dis.sh"

**Comment by QingyongHu** [comment]
Hi @DRosemei, thanks for your interest in our work.

I have tried to run the code in my pc and it works very well. It is a little bit weird that it cannot generate the `test` folder on your computer. I suppose it could be caused by the permissions, but anyway, you have already found the way to make it work. 

Good lucks!

**Comment by honggesmile** [comment]
> I have solved this problem.
> I use `python -B main_S3DIS.py --gpu 0 --mode test --test_area 1 --model_path results/Log_2020-03-31_07-53-08/snapshots/snap-33501` to test Area1 and test other areas respectively. But I still do not know why it did not work in "jobs_6_fold_cv_s3dis.sh"

hi,when i run :`python -B main_S3DIS.py --gpu 0 --mode test --test_area 1 --model_path /media/kfr/Elements\ SE/RandLA-Net/RandLA-Net/models/S3DIS/Area_1/snap-26001
`,An error has occurred，do you know how to slove it？ thanks for your help.
error :`Preparing reprojected indices for testing
Initiating input pipelines
WARNING:tensorflow:From /media/kfr/Elements SE/ppp/RandLA-Net/RandLANet.py:265: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Model restored from /media/kfr/Elements SE/RandLA-Net/RandLA-Net/models/S3DIS/Area_1/snap-26001
Traceback (most recent call last):
  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

AttributeError: 'list' object has no attribute 'argmin'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 418, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 114, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence


	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_4"](arg0)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_S3DIS.py", line 254, in <module>
    tester.test(model, dataset)
  File "/media/kfr/Elements SE/ppp/RandLA-Net/tester_S3DIS.py", line 78, in test
    stacked_probs, stacked_labels, point_idx, cloud_idx = self.sess.run(ops, {model.is_training: False})
  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)

AttributeError: 'list' object has no attribute 'argmin'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 418, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 114, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence


	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_4"](arg0)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
`

**Comment by DRosemei** [comment]
@honggesmile Have you generated model like below?
![image](https://user-images.githubusercontent.com/27892562/79689659-dccff200-8288-11ea-8e1d-d331f8eb6744.png)

 I found that your result path is so weird and  it raised an error, "ValueError: attempt to get argmin of an empty sequence".

**Comment by Ailce8862** [comment]
> @honggesmile Have you generated model like below?
> ![image](https://user-images.githubusercontent.com/27892562/79689659-dccff200-8288-11ea-8e1d-d331f8eb6744.png)
> 
> I found that your result path is so weird and it raised an error, "ValueError: attempt to get argmin of an empty sequence".
My running results are the same, but I don’t know how to test the results.Can you tell me？

**Comment by QingyongHu** [comment]
@DRosemei @Ailce8862 Can you please check if you have successfully loaded the data?

**Comment by Ailce8862** [comment]
> @DRosemei @Ailce8862 Can you please check if you have successfully loaded the data?

NO

**Comment by hansen7** [comment]
> > I have solved this problem.
> > I use `python -B main_S3DIS.py --gpu 0 --mode test --test_area 1 --model_path results/Log_2020-03-31_07-53-08/snapshots/snap-33501` to test Area1 and test other areas respectively. But I still do not know why it did not work in "jobs_6_fold_cv_s3dis.sh"
> 
> hi,when i run :`python -B main_S3DIS.py --gpu 0 --mode test --test_area 1 --model_path /media/kfr/Elements\ SE/RandLA-Net/RandLA-Net/models/S3DIS/Area_1/snap-26001 `,An error has occurred，do you know how to slove it？ thanks for your help.
> error :
> 
> ```
> Preparing reprojected indices for testing
> Initiating input pipelines
> WARNING:tensorflow:From /media/kfr/Elements SE/ppp/RandLA-Net/RandLANet.py:265: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> 
> Future major versions of TensorFlow will allow gradients to flow
> into the labels input on backprop by default.
> 
> See `tf.nn.softmax_cross_entropy_with_logits_v2`.
> 
> /home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
>   "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
> Model restored from /media/kfr/Elements SE/RandLA-Net/RandLA-Net/models/S3DIS/Area_1/snap-26001
> Traceback (most recent call last):
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
>     return fn(*args)
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
> Traceback (most recent call last):
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
>     return getattr(obj, method)(*args, **kwds)
> 
> AttributeError: 'list' object has no attribute 'argmin'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
>     ret = func(*args)
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 418, in generator_py_func
>     values = next(generator_state.get_iterator(iterator_id))
> 
>   File "main_S3DIS.py", line 114, in spatially_regular_gen
>     cloud_idx = int(np.argmin(self.min_possibility[split]))
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
>     return _wrapfunc(a, 'argmin', axis=axis, out=out)
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
>     return _wrapit(obj, method, *args, **kwds)
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
>     result = getattr(asarray(obj), method)(*args, **kwds)
> 
> ValueError: attempt to get argmin of an empty sequence
> 
> 
> 	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_4"](arg0)]]
> 	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main_S3DIS.py", line 254, in <module>
>     tester.test(model, dataset)
>   File "/media/kfr/Elements SE/ppp/RandLA-Net/tester_S3DIS.py", line 78, in test
>     stacked_probs, stacked_labels, point_idx, cloud_idx = self.sess.run(ops, {model.is_training: False})
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
>     run_metadata_ptr)
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1110, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
>     run_metadata)
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: attempt to get argmin of an empty sequence
> Traceback (most recent call last):
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
>     return getattr(obj, method)(*args, **kwds)
> 
> AttributeError: 'list' object has no attribute 'argmin'
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
>     ret = func(*args)
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 418, in generator_py_func
>     values = next(generator_state.get_iterator(iterator_id))
> 
>   File "main_S3DIS.py", line 114, in spatially_regular_gen
>     cloud_idx = int(np.argmin(self.min_possibility[split]))
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 1172, in argmin
>     return _wrapfunc(a, 'argmin', axis=axis, out=out)
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
>     return _wrapit(obj, method, *args, **kwds)
> 
>   File "/home/kfr/anaconda3/envs/randlanet/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
>     result = getattr(asarray(obj), method)(*args, **kwds)
> 
> ValueError: attempt to get argmin of an empty sequence
> 
> 
> 	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], token="pyfunc_4"](arg0)]]
> 	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?,3], [?,?,3], [?,?,3], [?,?,3], [?,?,3], ..., <unknown>, [?,?,6], [?,?], [?,?], [?,?]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_INT32, DT_FLOAT, DT_INT32, DT_INT32, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
> ```

Hi, @honggesmile 
I've encountered the same issue, my solution is to change:
https://github.com/QingyongHu/RandLA-Net/blob/3aafa161f32730fa1a9bbd63d06afe8e18ce9ab9/main_S3DIS.py#L16
into `self.path='data/S3DIS'`, hope it helps:)

**Comment by vikas-shetty** [comment]
@hansen7 @QingyongHu 

even iam trying to use pretrained model for S3DIS dataset

correct me if iam wrong
1) if iam using pretrained model then i dont have to run these lines
     sh jobs_6_fold_cv_s3dis.sh
     python utils/6_fold_cv.py
2) i just run    python utils/data_prepare_s3dis.py     and i succeded
 but when i run   python -B main_S3DIS.py --gpu 0 --mode test --test_area 1  
i got into  below result



---------------------------------------------------------------------------------------------------------
Area_1_office_31_KDTree.pkl 7.4 MB loaded in 0.0s
Area_1_hallway_4_KDTree.pkl 0.7 MB loaded in 0.0s
Area_1_office_15_KDTree.pkl 0.9 MB loaded in 0.0s

Preparing reprojected indices for testing
Area_1_hallway_2 done in 0.0s
Area_1_hallway_5 done in 0.0s
Area_1_office_16 done in 0.0s
Area_1_office_18 done in 0.0s
Area_1_office_28 done in 0.0s
Area_1_office_20 done in 0.0s
Area_1_office_22 done in 0.0s
Area_1_hallway_1 done in 0.0s
Area_1_office_1 done in 0.0s
Area_1_office_14 done in 0.0s
Area_1_office_30 done in 0.0s
Area_1_office_7 done in 0.0s
Area_1_office_3 done in 0.0s
Area_1_office_26 done in 0.0s
Area_1_office_13 done in 0.0s
Area_1_office_5 done in 0.0s
Area_1_pantry_1 done in 0.0s
Area_1_office_11 done in 0.0s
Area_1_office_2 done in 0.0s
Area_1_office_9 done in 0.0s
Area_1_office_21 done in 0.0s
Area_1_office_10 done in 0.0s
Area_1_hallway_8 done in 0.0s
Area_1_conferenceRoom_1 done in 0.0s
Area_1_conferenceRoom_2 done in 0.0s
Area_1_hallway_6 done in 0.1s
Area_1_office_19 done in 0.0s
Area_1_WC_1 done in 0.0s
Area_1_office_17 done in 0.0s
Area_1_hallway_3 done in 0.0s
Area_1_hallway_7 done in 0.0s
Area_1_office_12 done in 0.0s
Area_1_office_4 done in 0.0s
Area_1_office_29 done in 0.0s
Area_1_copyRoom_1 done in 0.0s
Area_1_office_23 done in 0.0s
Area_1_office_8 done in 0.0s
Area_1_office_25 done in 0.0s
Area_1_office_27 done in 0.0s
Area_1_office_6 done in 0.0s
Area_1_office_24 done in 0.0s
Area_1_office_31 done in 0.1s
Area_1_hallway_4 done in 0.0s
Area_1_office_15 done in 0.0s
Initiating input pipelines
WARNING:tensorflow:From /home/vikas/RandLA-Net/RandLANet.py:265: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

/home/vikas/anaconda3/envs/randlanet/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:108: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
results/Log_2020-06-22_11-52-29/snapshots
Model restored from results/Log_2020-06-22_11-52-29/snapshots/snap-26001
Killed
---------------------------------------------------------------------------------------------------

process got killed 
let me know anyone can help

**Comment by hansen7** [comment]
hi @vikas-shetty this is warning, I've encountered, it is not the reason to kill your process

**Comment by fenfenglitech** [comment]
hi @Vikas-Shetty ,i got the testing process killed when i test on semantickitti sequences 13,19 and 21.have you sloved this problem,could you give me some suggestions?
