### ISSUE TITLE
when I run python utils/data_prepare_semantic3d.py and  install open3d, I meet a problem.

### ISSUE THREAD

**Issue by XueDoudou** [QingyongHu/RandLA-Net#82]
`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/xdd/.conda/envs/tfdd1/lib/python3.6/site-packages/open3d/open3d_pybind.cpython-36m-x86_64-linux-gnu.so)`

I download GLIBC_2.27, and it can't work.

who can help me? thanks

**Comment by QingyongHu** [comment]
Hi @XueDoudou, thanks for your interest in our work!

May I ask which version of open3d you have installed?

**Comment by XueDoudou** [comment]
@QingyongHu , thanks for your reply!
I install the open3d directly with : pip install open3d.
I run the command, and enter the python env, input : import open3d, an error occurred. It is that error I meet in the question.

the Detail is in the picture.
![detail](https://user-images.githubusercontent.com/42439355/84031248-ee4f9380-a9c7-11ea-9c54-84e37194f3a6.png)

**Comment by XueDoudou** [comment]
@QingyongHu  If you can't see the image, the detail is :
`>>>import open3d`
`Traceback (most recent call last):`
`File "<stdin>", line 1, in <module>`
`File "/home/xdd/.conda/envs/tfdd1/lib/python3.6/site-packages/open3d/__init__.py", line 47, in <module>`
`from open3d.open3d_pybind import camera`
`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version '**GLIBC_2.27**' not found (required by /home/xdd/.conda/envs/tfdd1/lib/python3.6/site-packages/open3d/open3d_pybind.cpython-36m-x86_64-linux-gnu.so)`

Looking forward to you reply!

**Comment by XueDoudou** [comment]
ok, thanks! 
I try it now!

**Comment by XueDoudou** [comment]
ok, thanks! 
I try it now!

**Comment by XueDoudou** [comment]
@QingyongHu , I want to ask one question:
if I only have the 16GB RAM, May I run the Semantic3D dateset in my computer? I have seen the Note:
`Preferably with more than 64G RAM to process this dataset due to the large volume of point cloud`
, but Is there any possibility to do this?
