### ISSUE TITLE
运行S3DIS数据时，epoch为0

### ISSUE THREAD

**Issue by wlwnwafu** [QingyongHu/RandLA-Net#83]
亲爱的胡老师：
         您好，我是一名本科生，最近在看您的文章，在运行的时候“sh jobs_6_fold_cv_s3dis.sh”这一条命令时，遇到了
“***EPOCH 0****
Caught a NaN error :
3
2 root error(s) found.
  (0) Invalid argument: ValueError: attempt to get argmin of an empty sequence
Traceback (most recent call last):

  File "/home/wlw/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/home/wlw/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "main_S3DIS.py", line 114, in spatially_regular_gen
    cloud_idx = int(np.argmin(self.min_possibility[split]))

  File "<__array_function__ internals>", line 6, in argmin

  File "/home/wlw/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1267, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "/home/wlw/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/home/wlw/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence”这个错误，学生刚刚进入学习阶段，或许范一些很简单的错误，但还是希望您能不吝赐教，解答一下，十分感谢您的帮助。

**Comment by Mrwangnwafu** [comment]
查看log，里边是空的

**Comment by wlw-nwafu** [comment]
也就是说训练时，epoch里边都是空的

**Comment by wlw-nwafu** [comment]
@QingyongHu

**Comment by MrHynes** [comment]
你好 请问问题解决了吗？

**Comment by wlw-nwafu** [comment]
> 你好 请问问题解决了吗？

是的，这是数据路径的问题，你要检查所有文件的数据路径，要把“/data/.......”的“/”去掉就可以解决了

**Comment by MrHynes** [comment]
> > 你好 请问问题解决了吗？
> 
> 是的，这是数据路径的问题，你要检查所有文件的数据路径，要把“/data/.......”的“/”去掉就可以解决了

已解决，非常感谢！

**Comment by Yaomeng-meng** [comment]
> 亲爱的胡老师：
> 您好，我是一名本科生，最近在看您的文章，在运行的时候“sh jobs_6_fold_cv_s3dis.sh”这一条命令时，遇到了
> “_**EPOCH 0**_*
> Caught a NaN error :
> 3
> 2 root error(s) found.
> (0) Invalid argument: ValueError: attempt to get argmin of an empty sequence
> Traceback (most recent call last):
> 
> File "/home/wlw/.local/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in **call**
> ret = func(*args)
> 
> File "/home/wlw/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
> values = next(generator_state.get_iterator(iterator_id))
> 
> File "main_S3DIS.py", line 114, in spatially_regular_gen
> cloud_idx = int(np.argmin(self.min_possibility[split]))
> 
> File "<**array_function** internals>", line 6, in argmin
> 
> File "/home/wlw/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1267, in argmin
> return _wrapfunc(a, 'argmin', axis=axis, out=out)
> 
> File "/home/wlw/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
> return _wrapit(obj, method, *args, **kwds)
> 
> File "/home/wlw/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
> result = getattr(asarray(obj), method)(*args, **kwds)
> 
> ValueError: attempt to get argmin of an empty sequence”这个错误，学生刚刚进入学习阶段，或许范一些很简单的错误，但还是希望您能不吝赐教，解答一下，十分感谢您的帮助。

同学你好，我目前也在跑这个网络，想请教你一些问题，方便的话请加一下我的微信：Yaomengmeng_1996

**Comment by YuhangJi** [comment]
> > 你好 请问问题解决了吗？
> 
> 是的，这是数据路径的问题，你要检查所有文件的数据路径，要把“/data/.......”的“/”去掉就可以解决了

谢谢你，我的异常是计算出了NaN，也是路径的问题，/data...忘记改了 hahha

**Comment by xlxlqqq** [comment]
I think I have solved the problem. 
1. When preparing the data by runing "python utils/data_prepare_s3dis.py", make sure the "/data/s3dis/xxx" in line14 is changed to "data/s3dis".
2.  As well, change the "/data/s3dis" to "data/S3DIS" in the "main_S3DIS.py". (line 16)
